name: Create Tag on Merge

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Tag Version
        id: set_tag
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"

          # Extract the version numbers
          major=$(echo $latest_tag | awk -F. '{print $1}' | sed 's/v//')
          minor=$(echo $latest_tag | awk -F. '{print $2}')
          patch=$(echo $latest_tag | awk -F. '{print $3}')

          # Increment the patch version
          new_patch=$((patch + 1))
          new_tag="v${major}.${minor}.${new_patch}"
          echo "New tag: $new_tag"

          # Output the new tag
          echo "tag=$new_tag" >> $GITHUB_ENV

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag $tag
          git push origin $tag
